const fs=require('node:fs');
const {courses,sources,rounds}=require('./content');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const allQ=courses.flatMap(c=>c.questions.map((q,i)=>({...q,id:`${c.id}-q${i}`,course:c.id,courseTitle:c.title})));
const countS=courses.reduce((n,c)=>n+c.sections.length,0);
const link=(id,text)=>`<a href="${id}.html">${esc(text)}</a>`;
const code=s=>s?`<pre tabindex="0" role="group" aria-label="코드 예제"><code>${esc(s)}</code></pre>`:'';
const nav=[['index','학습 시작'],['plan','33일 학습 계획'],['rounds','2024~2026 기출 지도'],...courses.map(c=>[c.id,c.title]),['practice','문제은행·오답'],['mock','20문항 모의 연습'],['cheatsheet','시험 직전 압축본'],['sources','출처·수록 범위']];
function shell(id,title,sub,body){return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="description" content="2024~2026 공개 복원 주제 기반 정보처리기사 실기 학습 노트. C Java Python SQL과 이론, 해설형 문제."><title>${esc(title)} · 실기 공부방</title><link rel="stylesheet" href="styles.css"><script src="search-data.js" defer></script><script src="app.js" defer></script></head><body data-page="${id}"><a class="skip" href="#main">본문으로 건너뛰기</a><div class="nav-scrim" hidden></div><aside class="sidebar" aria-label="전체 학습 메뉴"><div class="mobile-nav-head"><span>전체 학습 메뉴</span><button class="mobile-close" type="button" aria-label="학습 메뉴 닫기">닫기</button></div><a class="brand" href="index.html"><span class="brand-mark">실기</span><span>개발자의 실기 공부방<small>정보처리기사 · 2026</small></span></a><nav id="navigation" aria-label="학습 목차">${nav.map(([n,t],i)=>`${i===3?'<p class="nav-group">과목별 개념과 연습</p>':''}${i===15?'<p class="nav-group">복습 도구</p>':''}<a href="${n}.html" ${id===n?'aria-current="page"':''}>${esc(t)}${courses.some(c=>c.id===n)?`<span class="nav-done" data-course="${n}"></span>`:''}</a>`).join('')}</nav><div class="sidebar-foot">목표일 <strong>2026.10.25 (일)</strong><small>자료 기준 2026.09.26</small></div></aside><div class="workspace"><header class="topbar"><button class="mobile-toggle" type="button" aria-expanded="false" aria-controls="navigation" aria-label="전체 학습 메뉴 열기">목차</button><a class="mobile-brand" href="index.html">실기 공부방</a><span class="desktop-motto">READ · TRACE · RECALL</span><div><button id="search-toggle" aria-expanded="false" aria-controls="search-panel">검색 <kbd>/</kbd></button><button id="print-page">인쇄</button></div></header><section id="search-panel" hidden aria-label="전체 검색"><label for="global-search">개념·문제 검색</label><input id="global-search" type="search" placeholder="예: 포인터, 오버라이딩, 정규화" autocomplete="off"><div id="search-results" aria-live="polite"></div></section><main id="main"><div class="page-heading"><p class="eyebrow">${id==='index'?'33일, 매일 한 걸음':'정보처리 실무 · 학습 노트'}</p><h1>${esc(title)}</h1><p class="lead">${esc(sub)}</p></div>${body}</main><footer>직접 쓴 개념 설명과 창작 연습문제 · <a href="sources.html">출처와 확인 범위</a><span>진도는 이 브라우저에 저장됩니다.</span></footer></div><nav class="mobile-dock" aria-label="빠른 메뉴"><a href="index.html" ${id==='index'?'aria-current="page"':''}>홈</a><a href="plan.html" ${id==='plan'?'aria-current="page"':''}>계획</a><button class="dock-menu" type="button">과목</button><a href="practice.html" ${id==='practice'?'aria-current="page"':''}>문제</a><a href="mock.html" ${id==='mock'?'aria-current="page"':''}>모의</a></nav><div class="toast" role="status" aria-live="polite"></div><noscript><p class="noscript">개념과 정답·해설은 JavaScript 없이도 읽을 수 있습니다. 검색·진도·문제은행은 JavaScript를 켜 주세요.</p></noscript></body></html>`;}
const write=(id,title,sub,body)=>fs.writeFileSync(id+'.html',shell(id,title,sub,body));
function question(q,i){return `<article class="question" id="${q.id}" data-q="${q.id}"><div class="question-meta"><span>${esc(q.courseTitle)} · ${esc(q.level)} · 창작 ${String(i+1).padStart(2,'0')}</span><span class="q-state" data-state="${q.id}">미풀이</span></div><h3>${esc(q.title)}</h3><p>${esc(q.prompt)}</p>${code(q.code)}<label class="answer-label" for="answer-${q.id}">내 답안</label><textarea id="answer-${q.id}" data-answer="${q.id}" rows="2" placeholder="실행하지 말고 먼저 답을 적어보세요."></textarea><details class="solution"><summary>정답과 풀이 확인</summary><div><p class="answer"><strong>정답</strong> <span>${esc(q.answer).replace(/\n/g,'<br>')}</span></p><p>${esc(q.explanation)}</p><div class="rating"><span>해설과 비교해 직접 채점</span><button data-rate="correct" data-id="${q.id}">맞혔어요</button><button data-rate="wrong" data-id="${q.id}">다시 풀래요</button><button data-rate="clear" data-id="${q.id}">기록 해제</button></div></div></details></article>`;}
write('index','아는 개발에서,\n맞히는 실기로.','3년차 웹 개발자를 위한 C·Java·Python 입문과 정보처리기사 실기 전 범위 핵심 노트.',`
<section class="start-panel"><div><span class="tag">2026.09.22 → 10.24 학습</span><h2>오늘은 코드 읽기부터.</h2><p>개념을 읽고, 실행 흐름을 손으로 적고, 해설을 덮은 채 다시 풀어보세요. 언어는 매일, 이론은 짧게 반복합니다.</p><a class="button primary" href="basics.html">첫 과목 시작하기 →</a><a class="text-link" href="plan.html">날짜별 계획 보기</a></div><div class="date-block"><strong>33</strong><span>시험 전 학습일</span><small>10월 25일 시험 목표</small></div></section>
<div class="stats"><div><strong>${courses.length}</strong><span>학습 단원</span></div><div><strong>${countS}</strong><span>핵심 개념</span></div><div><strong>${allQ.length}</strong><span>해설형 창작 문제</span></div><div><strong>8</strong><span>공개 복원 회차</span></div></div>
<section class="section"><h2>이 자료를 읽는 순서</h2><p>기본 문법이 낯선 언어는 순서대로, 익숙한 SQL과 이론은 문제를 먼저 풀어 약점을 확인하세요. 아래 묶음은 공부를 위한 분류이며 공식 시험의 별도 과목·배점 구분이 아닙니다.</p><div class="course-grid">${courses.map((c,i)=>`<a class="course-link" href="${c.id}.html"><span class="course-num">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(c.title)}</h3><p>${esc(c.subtitle)}</p><small>${c.sections.length}개 개념 · ${c.questions.length}문제 <span data-course-progress="${c.id}"></span></small></div><span aria-hidden="true">↗</span></a>`).join('')}</div></section>
<section class="section split"><div><h2>하루 2시간 기준</h2><ol class="routine"><li><strong>15분</strong> 어제 오답을 해설 없이 다시 풀기</li><li><strong>60분</strong> 언어 개념 + 코드 추적 3~5문제</li><li><strong>30분</strong> SQL 또는 이론 단답 회상</li><li><strong>15분</strong> 틀린 이유 한 줄 + 다음 복습 표시</li></ol><p class="muted">주말에는 3시간을 확보해 누적 복습. 시간 배분은 학습 제안이며 공식 출제 비중이 아닙니다.</p></div><div class="note"><h2>시험에 맞춘 목표</h2><p>공식 실기는 정보처리 실무 <strong>필답형 2시간 30분</strong>, 합격 기준은 <strong>100점 중 60점 이상</strong>입니다. <a href="${sources[0].url}" target="_blank" rel="noopener">Q-Net 안내</a></p><p>학습 목표는 75~80점 수준의 안정성으로 잡습니다. 코딩만 풀거나 단답만 외우지 말고 SQL·계산형까지 함께 준비하세요.</p></div></section>
<section class="notice"><h2>2026년은 1·2회까지만 반영했습니다</h2><p>2024년 1~3회, 2025년 1~3회, 2026년 1~2회 공개 복원의 확인된 주제를 참고했습니다. 복원은 공식 원문·정답이 아니며, 이 자료의 문제는 모두 새로 만든 연습문제입니다. 2026년 3회 실기시험은 Q-Net 공식 일정 기준 2026.10.24~11.13에 시행되며, 2026.09.26 기준 아직 시행 전이라 복원 문제를 수록하지 않았습니다.</p><a href="rounds.html">회차별 주제와 연결 단원 →</a></section>
<section class="section"><h2>내 학습 현황</h2><div id="dashboard-progress" class="note"></div><p>검색·답안·오답·진도는 서버로 전송하지 않습니다. 같은 폴더·브라우저에서 사용하세요. file:// 저장 동작은 브라우저에 따라 달라질 수 있으므로 중요한 기록은 백업해 두세요.</p><div class="actions"><button id="export-progress">학습 기록 백업</button><button id="import-button">백업 불러오기</button><input type="file" id="import-progress" accept="application/json,.json" hidden></div></section>`);

courses.forEach((c,ci)=>{
const refs=rounds.filter(r=>r[3].includes(c.id));
const body=`<p class="intro">${esc(c.intro)}</p><div class="lesson-layout"><div class="lesson-main"><section class="note"><strong>이번 단원 완료 기준</strong><p>핵심 규칙을 설명하고, 연습문제의 답과 이유를 해설 없이 적을 수 있으면 체크하세요. 이해 체크와 정답 기록은 별도로 저장됩니다.</p><span data-course-progress="${c.id}"></span></section>${c.sections.map((s,i)=>`<section class="concept" id="section-${i}"><div class="concept-heading"><span class="section-number">${String(i+1).padStart(2,'0')}</span><h2>${esc(s.title)}</h2></div><p>${esc(s.body)}</p>${code(s.code)}<div class="essential"><strong>꼭 기억할 것</strong><p>${esc(s.must)}</p></div><p class="pitfall"><strong>헷갈리는 지점</strong> ${esc(s.trap)}</p><label class="check-label"><input type="checkbox" data-done="${c.id}-s${i}"> 해설 없이 설명할 수 있어요</label></section>`).join('')}<section class="section" id="exercises"><h2>직접 풀어보기 <span class="muted">${c.questions.length}문제</span></h2><p>모두 유형 연습을 위해 직접 만든 문제입니다. C 예제의 printf·strlen은 필요한 표준 헤더가 포함된 상황을 가정합니다. Java는 표시된 클래스·main 위치에서 실행합니다. 단답은 동의어가 있을 수 있어 자동 판정 대신 자기 채점을 사용합니다.</p>${allQ.filter(q=>q.course===c.id).map(question).join('')}</section><section class="note"><h2>기출과 연결하기</h2>${refs.length?refs.map(r=>`<p><a href="rounds.html#round-${r[0]}">${r[0].replace('-','년 ')}회</a> · ${esc(r[1])}</p>`).join(''):'<p>코드 공통 원리 또는 공식 출제경향을 보완하는 단원입니다. 특정 회차의 직접 출제를 주장하지 않습니다.</p>'}<p><a href="sources.html">문법 문서·출처·확인 범위 보기</a></p></section><div class="next-prev"><a href="${ci?courses[ci-1].id:'index'}.html">← ${ci?esc(courses[ci-1].title):'학습 시작'}</a><a href="${ci<courses.length-1?courses[ci+1].id:'practice'}.html">${ci<courses.length-1?esc(courses[ci+1].title):'문제은행'} →</a></div></div><aside class="toc" aria-label="이 페이지 목차"><strong>이 페이지에서</strong>${c.sections.map((s,i)=>`<a href="#section-${i}">${esc(s.title)}</a>`).join('')}<a href="#exercises">연습문제 ${c.questions.length}개</a><a href="cheatsheet.html#${c.id}">압축 복습</a></aside></div>`;
write(c.id,c.title,c.subtitle,body);
});

const days=[
['기초 진단·코드 읽기','basics','공통 4문제 + 언어별 처음 2문제를 풀고 막히는 문법 표시'],
['C 자료형·조건·반복','c','개념 1·8, 문제 1·9·10. 출력 형식과 비트 연산 추적'],
['C 포인터 입문','c','개념 2·3, 문제 1·2·3. 주소와 값 그림 그리기'],
['C 문자열·이차원 배열','c','개념 4·5, 문제 3·6·7. 인덱스를 표로 기록'],
['C 함수·static','c','개념 6, 문제 4·5·11. 호출마다 지역변수 구분'],
['C 구조체·트리','c','개념 7, 문제 8·12. next/left/right를 화살표로 그리기'],
['C 누적 복습 + SQL 기초','sql','C 오답 전부 재풀이, SQL 개념 1~3'],
['Java 문법·문자열','java','개념 1·2·7, 문제 1·6·9'],
['Java 상속·필드','java','개념 3, 문제 2·12. 선언 타입과 실제 객체 표'],
['Java 생성자·static','java','개념 5·6, 문제 3·4·11'],
['Java 오버로드·참조 전달','java','개념 4·6, 문제 5·7·8'],
['Java 재귀·전체 복습','java','개념 8, 문제 10과 Java 오답 재풀이'],
['Python 기본·슬라이스','python','개념 1·2, 문제 1·2·3·9'],
['Python 컬렉션·얕은 복사','python','개념 3·4, 문제 4·5·10'],
['Python 함수·딕셔너리','python','개념 5~7, 문제 6·7·8·11·12'],
['세 언어 혼합 복습','practice','C 4문제, Java 4문제, Python 4문제. 틀린 규칙 비교표 작성'],
['SQL 조인·NULL','sql','개념 3·4, 문제 1·3·4·6·10. 결과 행 직접 나열'],
['SQL 서브쿼리·제약','sql','개념 5~7, 문제 2·5·7·8·9'],
['DB 키·정규화','database','전 개념과 문제. 부분/이행 종속 사례 직접 작성'],
['요구사항·UML·응집/결합','design','개념 1~4·8, 해당 연습문제 풀이'],
['디자인 패턴·테스트','testing','설계 개념 5~7 + 테스트 전 개념, 용어를 가리고 회상'],
['네트워크·서브넷','network','주소 계산 전부 풀이. 프로토콜·계층 연결'],
['OS 스케줄링·페이지 교체','os','시간축과 프레임 표 작성. SRT/LRU/FIFO 비교'],
['보안·신기술·연계','security','보안 전 개념 + 통합 구현 개념 1~5'],
['2024년 회차 복습','rounds','2024 1~3회 원문 링크에서 문제 확인 + 연결 단원 오답'],
['2025년 회차 복습','rounds','2025 1~3회 원문 링크에서 문제 확인 + 연결 단원 오답'],
['2026년 회차 복습','rounds','2026 1·2회 주제 점검. 외부 원문과 해설 비교'],
['모의 연습 1','mock','150분 제한으로 20문항. 자기 채점 후 약점 기록'],
['모의 연습 1 오답 보완','practice','오답 필터에서 재풀이, 각 언어 취약 개념 다시 읽기'],
['모의 연습 2','mock','다른 20문항 구성. 답안을 먼저 쓰고 마지막에 해설 열기'],
['남은 취약점 집중','practice','다시 풀래요 항목을 해설 없이 풀이. 이유까지 설명'],
['전체 압축 회상','cheatsheet','공식·용어·언어 함정을 빈 종이에 재현'],
['가벼운 최종 복습','cheatsheet','새 주제 대신 오답과 압축본 확인. 수험표·신분증·시간·장소 확인']
];
write('plan','33일 학습 계획','2026년 9월 22일 시작, 10월 24일 마무리. 하루 2시간을 기본으로 잡았습니다.',`<div class="note"><strong>평일 2시간 · 여유 있는 날 3시간</strong><p>최소 루틴은 오답 15분 + 언어 60분 + 이론/SQL 30분 + 기록 15분입니다. 하루 놓치면 다음 날 모든 분량을 몰아넣기보다 언어 루틴을 유지하고 누적 복습일에 보완하세요. 시험일은 사용자 지정 10월 25일이며 개인 일정은 수험표를 기준으로 합니다.</p></div><div class="plan-list">${days.map((d,i)=>{const date=new Date(Date.UTC(2026,8,22+i));return `<article class="day"><div class="day-date"><strong>${date.getUTCMonth()+1}.${String(date.getUTCDate()).padStart(2,'0')}</strong><span>${['일','월','화','수','목','금','토'][date.getUTCDay()]}요일 · D-${33-i}</span></div><div><h2>${esc(d[0])}</h2><p>${esc(d[2])}</p><a href="${d[1]}.html">오늘 공부 열기 →</a></div><label class="check-label"><input type="checkbox" data-done="plan-${i}"> 완료</label></article>`}).join('')}</div>`);

write('rounds','2024~2026 기출 지도','공개 복원 8개 회차에서 확인한 대표 주제와 이 학습 자료의 연결 단원.',`<section class="notice"><h2>읽는 기준</h2><p>아래는 회차 전체 문항 목록이나 공식 출제빈도 통계가 아닙니다. 공개 페이지에서 확인한 대표 주제를 짧게 정리했습니다. 복원 특성상 표현·문항 번호·코드가 실제 시험과 다를 수 있습니다. 원문 문제를 풀 때는 아래 출처로 이동하세요.</p><p>2026년 3회 실기시험은 Q-Net 공식 일정 기준 2026.10.24~11.13 시행이며, 2026.09.26 기준 아직 미시행입니다. “최근 3개년”을 완료된 9회차로 계산하지 않았습니다.</p></section>${rounds.map(r=>`<section class="round section" id="round-${r[0]}"><div class="round-title"><h2>${r[0].replace('-','년 ')}회</h2><span class="tag">비공식 공개 복원</span></div><h3>${esc(r[1])}</h3><p>${esc(r[2])}</p><div class="link-row">${r[3].map(id=>link(id,courses.find(c=>c.id===id).title)).join('')}</div><p><a href="${sources.find(s=>s.id===r[0]).url}" target="_blank" rel="noopener">해당 회차 원문·복원 출처 열기 ↗</a></p></section>`).join('')}<section class="note"><h2>학습 우선순위는 이렇게 정했습니다</h2><p>사용자의 언어 경험 공백을 반영해 C·Java·Python을 먼저 배치했습니다. SQL과 계산형은 직접 결과를 구하는 연습, 이론은 정의를 보고 용어를 쓰는 연습을 병행합니다. 특정 주제의 다음 시험 출제를 보장하거나 확인하지 않은 빈도 수치를 붙이지 않았습니다.</p></section>`);

write('practice','문제은행·오답 노트',`${allQ.length}개 창작 문제를 과목·난이도·풀이 상태로 골라 연습하세요.`, `<div class="filterbar"><label>과목<select id="filter-course"><option value="all">전체 과목</option>${courses.map(c=>`<option value="${c.id}">${esc(c.title)}</option>`).join('')}</select></label><label>풀이 상태<select id="filter-state"><option value="all">전체</option><option value="new">미풀이</option><option value="wrong">다시 풀래요</option><option value="correct">맞혔어요</option></select></label><label>난이도<select id="filter-level"><option value="all">전체</option><option>기본</option><option>응용</option><option>심화</option></select></label><button id="shuffle">순서 섞기</button></div><p id="question-count" role="status"></p><div id="question-bank"></div><script src="questions.js" defer></script>`);
write('mock','20문항 모의 연습','150분 안에 답안을 먼저 적고, 제출 후 해설과 비교해 자기 채점합니다.',`<section class="note"><h2>학습용 혼합 구성</h2><p>C 3 · Java 3 · Python 2 · SQL 3 · 이론 9문제를 문제은행에서 무작위로 뽑습니다. 공식 회차 배점·분포를 재현한 모의고사가 아닙니다. 기존 문제은행과 겹칠 수 있으므로 실전 회차는 기출 지도의 외부 복원 자료도 함께 이용하세요.</p><p>채점은 한 문제 5점의 학습용 기준입니다. 실제 시험의 부분점수·채점기준을 대체하지 않습니다. 이 페이지의 해설은 제출하거나 시간이 끝나면 열립니다.</p></section><div class="mockbar"><strong id="timer" role="timer" aria-label="남은 시간">150:00</strong><button class="primary" id="start-mock">20문항 시작</button><button id="submit-mock" disabled>답안 제출·해설 보기</button><span id="mock-status" role="status">아직 시작하지 않았습니다.</span></div><div id="mock-results" hidden></div><div id="mock-questions"></div><script src="questions.js" defer></script>`);

write('cheatsheet','시험 직전 압축본','처음 공부할 때의 대체재보다, 이미 배운 규칙을 빠르게 떠올리는 회상용으로 사용하세요.',`<div class="notice"><h2>마지막 48시간의 기준</h2><p>답을 보고 아는 느낌보다 빈 종이에 직접 쓸 수 있는지를 확인하세요. 각 단원의 “꼭 기억할 것”을 모았습니다. 자세한 설명과 반례는 해당 단원으로 돌아가세요.</p></div>${courses.map(c=>`<section class="section" id="${c.id}"><h2>${esc(c.title)} <a class="small-link" href="${c.id}.html">상세 학습 →</a></h2><dl class="compact">${c.sections.map(s=>`<dt>${esc(s.title)}</dt><dd>${esc(s.must)}</dd>`).join('')}</dl></section>`).join('')}<section class="note"><h2>답안 제출 전 확인</h2><ul><li>출력의 공백·줄바꿈·대소문자·소수점 자릿수를 확인했다.</li><li>문제에서 요구한 빈칸의 순서와 답안의 순서가 같다.</li><li>SQL은 NULL·중복·외부 조인의 미매칭 행을 확인했다.</li><li>계산형은 도착시간·선점·단위·반올림 조건을 확인했다.</li><li>서로 모순되는 여러 답을 함께 적지 않았다.</li></ul></section>`);

const coverage=[['요구사항 확인','design'],['데이터 입출력 구현','database'],['통합 구현','integration'],['서버프로그램 구현','design'],['인터페이스 구현','integration'],['화면 설계','design'],['애플리케이션 테스트','testing'],['SQL 응용','sql'],['소프트웨어 개발 보안','security'],['프로그래밍 언어 활용','basics'],['응용 SW 기초 기술','os'],['제품 소프트웨어 패키징','integration']];
write('sources','출처와 수록 범위','확인 기준일 2026.09.26 · 공식 정보, 공개 복원, 직접 작성한 학습 콘텐츠를 구분했습니다.',`<section class="section"><h2>자료의 성격</h2><ul><li><strong>공식 정보:</strong> Q-Net 종목 안내의 실기 방식·합격기준·출제경향과 2026 적용 기준 안내를 확인했습니다.</li><li><strong>회차 연결:</strong> 2024년 3회차, 2025년 3회차, 2026년 2회차의 공개 복원 페이지를 확인했습니다. 일부 코드 원문이 텍스트에 노출되지 않아 전체 160문항의 원문·정답을 완전 검증한 자료는 아닙니다.</li><li><strong>학습 설명:</strong> 공통 전산 개념을 웹 개발자 관점으로 직접 설명했습니다. 기출에서 확인한 주제 외에 공식 출제경향의 빈 영역을 보완했습니다.</li><li><strong>연습문제:</strong> ${allQ.length}개 모두 창작입니다. 원문 기출이나 공식 예상문제로 표시하지 않았습니다. 풀이 상태는 자기 채점이며 공식 채점을 대신하지 않습니다.</li><li><strong>완전성:</strong> 핵심 요약본입니다. 모든 NCS 세부 항목·모든 신기술 용어를 다루는 백과나 공식 교재의 대체물은 아닙니다.</li></ul></section><section class="section"><h2>공식 출제경향과 학습 단원</h2><div class="coverage">${coverage.map(([name,id])=>`<div><strong>${esc(name)}</strong>${link(id,courses.find(c=>c.id===id).title)}</div>`).join('')}</div><p>언어 활용은 C·Java·Python, 데이터 입출력은 DB·SQL, 응용 SW 기초는 OS·네트워크에 나누어 정리했습니다. 위 연결은 공부를 위한 재분류입니다.</p></section><section class="section"><h2>확인한 출처</h2>${sources.map(s=>`<article class="source" id="source-${s.id}"><span class="tag">${esc(s.type)}</span><h3><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.name)} ↗</a></h3><p>${esc(s.note)}</p></article>`).join('')}<article class="source"><span class="tag">공식 표준 안내</span><h3><a href="https://www.iso.org/standard/78176.html" target="_blank" rel="noopener">ISO/IEC 25010:2023 ↗</a></h3><p>2023 판은 제품 품질 특성 9개. <a href="https://committee.iso.org/standard/35733.html" target="_blank" rel="noopener">2011 판</a>의 8개 체계와 구분하여 주어진 판본을 읽도록 설명했습니다.</p></article></section><section class="note"><h2>사용과 기록 보관</h2><p>index.html을 브라우저로 열면 설치·로그인 없이 사용할 수 있습니다. HTML·CSS·JS를 같은 폴더에 두세요. 전체 개념은 페이지 안에 포함되어 인터넷이 없어도 읽을 수 있고, 외부 출처 링크에 접속할 때만 인터넷이 필요합니다.</p><p>진도와 답안은 localStorage에 저장합니다. 브라우저 데이터 삭제·시크릿 모드·폴더 이동·file:// 정책에 따라 보관이 달라질 수 있습니다. 홈의 기록 백업 기능으로 JSON을 저장할 수 있습니다. 더 안정적인 동일 출처 저장을 원하면 node serve.js 실행 후 http://127.0.0.1:4173 을 이용하세요.</p></section>`);

const search=courses.flatMap(c=>[...c.sections.map((s,i)=>({title:s.title,course:c.title,url:`${c.id}.html#section-${i}`,text:[s.body,s.must,s.trap].join(' ')})),...c.questions.map((q,i)=>({title:q.title,course:c.title,url:`${c.id}.html#${c.id}-q${i}`,text:q.prompt+' '+q.explanation}))]);
fs.writeFileSync('search-data.js','window.STUDY_SEARCH='+JSON.stringify(search)+';\nwindow.STUDY_COURSES='+JSON.stringify(courses.map(c=>({id:c.id,title:c.title,sections:c.sections.length,questions:c.questions.length})))+';');
fs.writeFileSync('questions.js','window.STUDY_QUESTIONS='+JSON.stringify(allQ)+';\nwindow.dispatchEvent(new Event("questions-ready"));');
fs.writeFileSync('README.md',`# 정보처리기사 실기 공부방\n\n시작: index.html을 Chrome 또는 Edge로 열기. 설치와 로그인은 필요하지 않습니다.\n\n- 12개 학습 단원, ${countS}개 개념, ${allQ.length}개 창작 문제\n- 2024~2026 공개 복원 8회차의 대표 주제 지도\n- 2026-09-22~2026-10-24 33일 계획\n- 검색, 자기 채점, 오답 필터, 진도/답안 저장, JSON 백업, 인쇄\n- 20문항/150분 학습용 모의 연습 (새로고침 시 모의 구성과 타이머 초기화)\n\n공식 원문 기출 전체 수록본이 아닙니다. 출처·검증 범위는 sources.html을 확인하세요.\n\n## 파일\nHTML/CSS/JS 파일을 같은 폴더에 두세요. 인터넷 없이 학습 가능하며 외부 출처 접속만 인터넷이 필요합니다.\n\n브라우저별 file:// localStorage 정책이 다르므로 학습 기록은 홈에서 주기적으로 백업하세요. 폴더 이동 시 기록이 공유되지 않을 수 있습니다. 안정적인 사용은 Node가 설치된 환경에서 \`node serve.js\` 후 http://127.0.0.1:4173 을 여는 방법도 있습니다.\n\n## 수정과 재생성\ncontent.js: 학습 콘텐츠 / build.js: HTML 생성 / app.js: 학습 기능 / styles.css: 화면\n\n\`node build.js\`로 정적 HTML과 검색·문제 데이터를 재생성합니다.\n`);
console.log(JSON.stringify({courses:courses.length,concepts:countS,questions:allQ.length,pages:nav.length}));


